### ISSUE TITLE
The red buttons need vertical spacing when stacked

### ISSUE THREAD

**Issue by CdrMarks** [tuscaloosaweb/twp-wordpress-theme#1]
When viewing the site on a mobile device, the red buttons buttons (Twitter, GitHub, and Meetup) need some vertical separation.

**Comment by bamadesigner** [comment]
Good catch. I added some more space around the buttons, with an emphasis on vertical space.

**Comment by CdrMarks** [comment]
Test

**Comment by bamadesigner** [comment]
What are you testing?
